site_name: wags documentation
site_description: Web Agent Gateway System - Middleware orchestration for MCP servers
site_author: WAGS Team
site_url: https://chughtapan.github.io/wags/
repo_url: https://github.com/chughtapan/wags
repo_name: chughtapan/wags
edit_uri: edit/main/docs/

theme:
  name: material
  favicon: assets/images/wags-logo.png
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - toc.integrate
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.annotate
    - content.code.copy

nav:
  - Home: index.md
  - Quick Start: quickstart.md
  - Middleware:
    - Overview: middleware/overview.md
    - TodoList: middleware/todo.md
    - Roots: middleware/roots.md
    - Elicitation: middleware/elicitation.md
  - Benchmarks: benchmarks.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
      auto_title: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path:
        - docs
      check_paths: true
      restrict_base_path: true
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/chughtapan/wags
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/wags/

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js